### ISSUE TITLE
liner power transfer

### ISSUE THREAD

**Issue by Spireneusz** [stevenbennett/DIYson#9]
Hi I today saw your diy project on yt, and I want to add 3 cents from my side.
I don't know if you familiar with electrical slip ring solution, basically it allows to transfer signals/power to rotating element. You can try to use this principle to make "linear slip ring" that will look something like in my sketch here: 
![DIYson Lamp](https://user-images.githubusercontent.com/122870400/212861215-832ccc21-78a4-4771-a5b3-07d358268f1e.png)

**Comment by stevenbennett** [comment]
@Spireneusz Thanks for sharing your idea and for the illustration. This has been suggested by a few people so I will keep it in mind. 

I'm going to close this "issue" for now since it's not an issue. Until now there hasn't been a better place to post ideas like this, so I have enabled the "Discussions" feature in this repository for future topics like this. Thanks again.
